<?php

class Kalinich_Action_Model_Post_Action extends Mage_Core_Model_Abstract
{

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('kalinich_action/post_action');
    }

}