<?php
$action = $this->getAction();
$collection = $this->getCollectionProducts();
?>
<div>
    <h2><?php echo $action->getName() . ' - ' . $action->getShortDescription(); ?></h2>
    <div>
        <img
                src="<?php echo $action->getImage()?>"
                alt="<?php echo $action->getName()?>"
                style="height: 300px; width: 300px; float:left; margin: 15px 15px 15px 0; "/>
        <?php echo $action->getDescription() ?>
    </div>

    <div class="category-products">
        <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
            <?php $i=0; foreach ($collection as $product): ?>
                <?php /*if ($i++%$_columnCount==0): ?>
                <?php endif*/ ?>

                <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">

                    <a href="<?php // echo Mage::getBaseUrl() . 'action/view/?id=' . $_action->getId(); ?>" title="<?php // echo $_action->getName(); ?>" class="product-image">
                        <?php $_imgSize = 200; ?>
                        <img id="action-collection-image-<?php // echo $_action->getId(); ?>"
                             src="<?php // echo $product->getImage()?>" style="height: 200px; width: 200px; "/>
                    </a>
                    <div class="product-info">
                        <h2 class="product-name">
                            <a
                                    href="<?php // echo Mage::getBaseUrl() . 'action/view/?id=' . $_action->getId(); ?>"
                                    title="<?php echo $product->getName(); ?>">
                                <?php echo $product->getName(); ?></a></h2>

                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
</div>